/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as FraudCheckRouteImport } from './routes/fraud-check'
import { Route as ComplaintRouteImport } from './routes/complaint'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiScoreRouteImport } from './routes/api/score'
import { Route as ApiProgressRouteImport } from './routes/api/progress'
import { Route as ApiLiveThreatsRouteImport } from './routes/api/live-threats'
import { Route as ApiCheckUrlRouteImport } from './routes/api/check-url'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiQuizModuleIdRouteImport } from './routes/api/quiz.$moduleId'
import { Route as ApiLessonsSlugRouteImport } from './routes/api/lessons.$slug'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminComplaintsRouteImport } from './routes/_authenticated/admin.complaints'
import { Route as AuthenticatedAdminCollegesRouteImport } from './routes/_authenticated/admin.colleges'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as ApiLessonsSlugModuleSlugRouteImport } from './routes/api/lessons.$slug.$moduleSlug'
import { Route as AuthenticatedLearnSlugModuleSlugRouteImport } from './routes/_authenticated/learn.$slug.$moduleSlug'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudCheckRoute = FraudCheckRouteImport.update({
  id: '/fraud-check',
  path: '/fraud-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintRoute = ComplaintRouteImport.update({
  id: '/complaint',
  path: '/complaint',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoreRoute = ApiScoreRouteImport.update({
  id: '/api/score',
  path: '/api/score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressRoute = ApiProgressRouteImport.update({
  id: '/api/progress',
  path: '/api/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveThreatsRoute = ApiLiveThreatsRouteImport.update({
  id: '/api/live-threats',
  path: '/api/live-threats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckUrlRoute = ApiCheckUrlRouteImport.update({
  id: '/api/check-url',
  path: '/api/check-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiQuizModuleIdRoute = ApiQuizModuleIdRouteImport.update({
  id: '/api/quiz/$moduleId',
  path: '/api/quiz/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonsSlugRoute = ApiLessonsSlugRouteImport.update({
  id: '/api/lessons/$slug',
  path: '/api/lessons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComplaintsRoute =
  AuthenticatedAdminComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCollegesRoute =
  AuthenticatedAdminCollegesRouteImport.update({
    id: '/colleges',
    path: '/colleges',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiLessonsSlugModuleSlugRoute =
  ApiLessonsSlugModuleSlugRouteImport.update({
    id: '/$moduleSlug',
    path: '/$moduleSlug',
    getParentRoute: () => ApiLessonsSlugRoute,
  } as any)
const AuthenticatedLearnSlugModuleSlugRoute =
  AuthenticatedLearnSlugModuleSlugRouteImport.update({
    id: '/learn/$slug/$moduleSlug',
    path: '/learn/$slug/$moduleSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/complaint': typeof ComplaintRoute
  '/fraud-check': typeof FraudCheckRoute
  '/programs': typeof ProgramsRoute
  '/team': typeof TeamRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/check-url': typeof ApiCheckUrlRoute
  '/api/live-threats': typeof ApiLiveThreatsRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/score': typeof ApiScoreRoute
  '/api/upload': typeof ApiUploadRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/': typeof LearnIndexRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/colleges': typeof AuthenticatedAdminCollegesRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/lessons/$slug': typeof ApiLessonsSlugRouteWithChildren
  '/api/quiz/$moduleId': typeof ApiQuizModuleIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/learn/$slug/$moduleSlug': typeof AuthenticatedLearnSlugModuleSlugRoute
  '/api/lessons/$slug/$moduleSlug': typeof ApiLessonsSlugModuleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/complaint': typeof ComplaintRoute
  '/fraud-check': typeof FraudCheckRoute
  '/programs': typeof ProgramsRoute
  '/team': typeof TeamRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/check-url': typeof ApiCheckUrlRoute
  '/api/live-threats': typeof ApiLiveThreatsRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/score': typeof ApiScoreRoute
  '/api/upload': typeof ApiUploadRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn': typeof LearnIndexRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/colleges': typeof AuthenticatedAdminCollegesRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/lessons/$slug': typeof ApiLessonsSlugRouteWithChildren
  '/api/quiz/$moduleId': typeof ApiQuizModuleIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/learn/$slug/$moduleSlug': typeof AuthenticatedLearnSlugModuleSlugRoute
  '/api/lessons/$slug/$moduleSlug': typeof ApiLessonsSlugModuleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/complaint': typeof ComplaintRoute
  '/fraud-check': typeof FraudCheckRoute
  '/programs': typeof ProgramsRoute
  '/team': typeof TeamRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/check-url': typeof ApiCheckUrlRoute
  '/api/live-threats': typeof ApiLiveThreatsRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/score': typeof ApiScoreRoute
  '/api/upload': typeof ApiUploadRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/': typeof LearnIndexRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/colleges': typeof AuthenticatedAdminCollegesRoute
  '/_authenticated/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/lessons/$slug': typeof ApiLessonsSlugRouteWithChildren
  '/api/quiz/$moduleId': typeof ApiQuizModuleIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/learn/$slug/$moduleSlug': typeof AuthenticatedLearnSlugModuleSlugRoute
  '/api/lessons/$slug/$moduleSlug': typeof ApiLessonsSlugModuleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/complaint'
    | '/fraud-check'
    | '/programs'
    | '/team'
    | '/admin'
    | '/dashboard'
    | '/api/chat'
    | '/api/check-url'
    | '/api/live-threats'
    | '/api/progress'
    | '/api/score'
    | '/api/upload'
    | '/learn/$slug'
    | '/learn/'
    | '/admin/bookings'
    | '/admin/colleges'
    | '/admin/complaints'
    | '/admin/content'
    | '/admin/team'
    | '/api/lessons/$slug'
    | '/api/quiz/$moduleId'
    | '/admin/'
    | '/learn/$slug/$moduleSlug'
    | '/api/lessons/$slug/$moduleSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/complaint'
    | '/fraud-check'
    | '/programs'
    | '/team'
    | '/dashboard'
    | '/api/chat'
    | '/api/check-url'
    | '/api/live-threats'
    | '/api/progress'
    | '/api/score'
    | '/api/upload'
    | '/learn/$slug'
    | '/learn'
    | '/admin/bookings'
    | '/admin/colleges'
    | '/admin/complaints'
    | '/admin/content'
    | '/admin/team'
    | '/api/lessons/$slug'
    | '/api/quiz/$moduleId'
    | '/admin'
    | '/learn/$slug/$moduleSlug'
    | '/api/lessons/$slug/$moduleSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/complaint'
    | '/fraud-check'
    | '/programs'
    | '/team'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/api/chat'
    | '/api/check-url'
    | '/api/live-threats'
    | '/api/progress'
    | '/api/score'
    | '/api/upload'
    | '/learn/$slug'
    | '/learn/'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/colleges'
    | '/_authenticated/admin/complaints'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/team'
    | '/api/lessons/$slug'
    | '/api/quiz/$moduleId'
    | '/_authenticated/admin/'
    | '/_authenticated/learn/$slug/$moduleSlug'
    | '/api/lessons/$slug/$moduleSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComplaintRoute: typeof ComplaintRoute
  FraudCheckRoute: typeof FraudCheckRoute
  ProgramsRoute: typeof ProgramsRoute
  TeamRoute: typeof TeamRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCheckUrlRoute: typeof ApiCheckUrlRoute
  ApiLiveThreatsRoute: typeof ApiLiveThreatsRoute
  ApiProgressRoute: typeof ApiProgressRoute
  ApiScoreRoute: typeof ApiScoreRoute
  ApiUploadRoute: typeof ApiUploadRoute
  LearnSlugRoute: typeof LearnSlugRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ApiLessonsSlugRoute: typeof ApiLessonsSlugRouteWithChildren
  ApiQuizModuleIdRoute: typeof ApiQuizModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud-check': {
      id: '/fraud-check'
      path: '/fraud-check'
      fullPath: '/fraud-check'
      preLoaderRoute: typeof FraudCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint': {
      id: '/complaint'
      path: '/complaint'
      fullPath: '/complaint'
      preLoaderRoute: typeof ComplaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/score': {
      id: '/api/score'
      path: '/api/score'
      fullPath: '/api/score'
      preLoaderRoute: typeof ApiScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress': {
      id: '/api/progress'
      path: '/api/progress'
      fullPath: '/api/progress'
      preLoaderRoute: typeof ApiProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-threats': {
      id: '/api/live-threats'
      path: '/api/live-threats'
      fullPath: '/api/live-threats'
      preLoaderRoute: typeof ApiLiveThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-url': {
      id: '/api/check-url'
      path: '/api/check-url'
      fullPath: '/api/check-url'
      preLoaderRoute: typeof ApiCheckUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/quiz/$moduleId': {
      id: '/api/quiz/$moduleId'
      path: '/api/quiz/$moduleId'
      fullPath: '/api/quiz/$moduleId'
      preLoaderRoute: typeof ApiQuizModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lessons/$slug': {
      id: '/api/lessons/$slug'
      path: '/api/lessons/$slug'
      fullPath: '/api/lessons/$slug'
      preLoaderRoute: typeof ApiLessonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/complaints': {
      id: '/_authenticated/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AuthenticatedAdminComplaintsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/colleges': {
      id: '/_authenticated/admin/colleges'
      path: '/colleges'
      fullPath: '/admin/colleges'
      preLoaderRoute: typeof AuthenticatedAdminCollegesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/lessons/$slug/$moduleSlug': {
      id: '/api/lessons/$slug/$moduleSlug'
      path: '/$moduleSlug'
      fullPath: '/api/lessons/$slug/$moduleSlug'
      preLoaderRoute: typeof ApiLessonsSlugModuleSlugRouteImport
      parentRoute: typeof ApiLessonsSlugRoute
    }
    '/_authenticated/learn/$slug/$moduleSlug': {
      id: '/_authenticated/learn/$slug/$moduleSlug'
      path: '/learn/$slug/$moduleSlug'
      fullPath: '/learn/$slug/$moduleSlug'
      preLoaderRoute: typeof AuthenticatedLearnSlugModuleSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminCollegesRoute: typeof AuthenticatedAdminCollegesRoute
  AuthenticatedAdminComplaintsRoute: typeof AuthenticatedAdminComplaintsRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminCollegesRoute: AuthenticatedAdminCollegesRoute,
  AuthenticatedAdminComplaintsRoute: AuthenticatedAdminComplaintsRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearnSlugModuleSlugRoute: typeof AuthenticatedLearnSlugModuleSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearnSlugModuleSlugRoute: AuthenticatedLearnSlugModuleSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiLessonsSlugRouteChildren {
  ApiLessonsSlugModuleSlugRoute: typeof ApiLessonsSlugModuleSlugRoute
}

const ApiLessonsSlugRouteChildren: ApiLessonsSlugRouteChildren = {
  ApiLessonsSlugModuleSlugRoute: ApiLessonsSlugModuleSlugRoute,
}

const ApiLessonsSlugRouteWithChildren = ApiLessonsSlugRoute._addFileChildren(
  ApiLessonsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComplaintRoute: ComplaintRoute,
  FraudCheckRoute: FraudCheckRoute,
  ProgramsRoute: ProgramsRoute,
  TeamRoute: TeamRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCheckUrlRoute: ApiCheckUrlRoute,
  ApiLiveThreatsRoute: ApiLiveThreatsRoute,
  ApiProgressRoute: ApiProgressRoute,
  ApiScoreRoute: ApiScoreRoute,
  ApiUploadRoute: ApiUploadRoute,
  LearnSlugRoute: LearnSlugRoute,
  LearnIndexRoute: LearnIndexRoute,
  ApiLessonsSlugRoute: ApiLessonsSlugRouteWithChildren,
  ApiQuizModuleIdRoute: ApiQuizModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
